global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Blackbox Exporter job to probe softuni.org
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]  # Use the http_2xx module from blackbox.yml
    static_configs:
      - targets:
          - https://softuni.org
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target   # Set the 'target' param for the probe endpoint
      - source_labels: [__param_target]
        target_label: instance         # Label 'instance' with the target URL
      - target_label: __address__
        replacement: localhost:9115    # Blackbox Exporter address
